name: Generate and Update Key Daily

on:
  schedule:
    - cron: '5 0 * * *' # Runs automatically everyday at 12:05 AM UTC
  workflow_dispatch: # Keeps the manual run button active

jobs:
  run-updater:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allows GitHub to write text files back into your repo
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Script One
        run: python update_key.py

      - name: Run Script Two
        run: python update_key_two.py

            # Keep your existing Run Script One and Run Script Two steps above here...

      - name: Run Script Three
        run: python update_key_three.py

      - name: Save Key Updates
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@://github.com"
          git add key1.txt key2.txt key3.txt
          git diff-index --quiet HEAD || git commit -m "Automated daily key updates"
          git push

